[package]
name = "ReSet-Lib"
version = "0.3.5"
edition = "2021"
description = "Data structure library for ReSet"
repository = "https://github.com/Xetibo/ReSet-Lib"
license = "GPL-3.0-only"

[dependencies]
directories-next = "2.0.0"
dbus = "0.9.7"
pulse = { version = "2.0", package = "libpulse-binding" }
